version: '3.6'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000

  node-red:
    build:
      dockerfile: ./docker/nodered.dockerfile
      context: .
    image: smart-building/node-red
    container_name: node-red
    restart: always
    environment:
      NODE_RED_CREDENTIAL_SECRET: smartbuilding123!nodered
    ports:
      - "1880:1880"
    networks:
      - "sb-network"
    volumes:
      - node-red-data:/data
    depends_on:
      - "database-postgres"

  database-postgres:
    build:
      dockerfile: ./docker/postgres.dockerfile
      context: .
    image: smart-building/postgres
    container_name: database-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: smartbuilding123!postgres
      POSTGRES_DB: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - "sb-network"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 4096000000 # (this means 4GB)

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - "sb-network"
    volumes:
      - mosquitto-config:/mosquitto/config

  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    networks:
      - "sb-network"
    volumes:
      - homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro

volumes:
  homeassistant-config:
  node-red-data:
  mosquitto-config:
  postgres-data:
    driver: local

networks:
  sb-network:
    driver: bridge
